---
auth:
  type: "basic"
  basic:
    # your email bitbucket
    username: ""
    # your api token bitbucket
    password: ""
included_workspaces: ["your_workspace_slug"]
refs_collector:
  # collect total branch at repo
  collect_total_branch: true
  # collect total tag at repo
  collect_total_tag: true
commit_collector:
  included_repository: ["your_workspace_slug/your_repo_slug"]
  # count total commit at repo
  collect_total_commit_repo: true
  # count total commit of user at repo
  collect_total_commit_user: true
